version: '3.7'

services:
  comet:
    build:
      context: .
      dockerfile: goim.Dockerfile
    image: devxz/goim
    restart: always
    env_file: .env
    ports:
      - "3101:3101"
      - "3102:3102"
      - "3109:3009"
    depends_on:
      - redis
      - zookeeper
      - kafka
      - discovery
    entrypoint: comet

  logic:
    build:
      context: .
      dockerfile: Dockerfile
    image: devxz/goim
    restart: always
    env_file: .env
    ports:
      - "3111:3111"
      - "3119:3119"
    depends_on:
      - redis
      - zookeeper
      - kafka
      - discovery
    entrypoint: logic

  job:
    build:
      context: .
      dockerfile: Dockerfile
    image: devxz/goim
    restart: always
    env_file: .env
    depends_on:
      - redis
      - zookeeper
      - kafka
      - discovery
    entrypoint: job

  discovery:
    build:
      context: .
      dockerfile: discovery.Dockerfile
    image: devxz/discovery
    restart: always
    ports:
      - "7171:7171"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9094:9094"
    environment:
      KAFKA_CREATE_TOPICS: "goim-push-topic"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181